language: c
os:
  - linux
  - osx
install:
  - |-
    ( cd
        git clone -b v0.4.2 --depth=1 https://github.com/gbdev/rgbds
        sudo make -C rgbds install
        rm -rf rgbds
    )
before_script:
  - |-
    function check_status() {
      if ! git diff-index --quiet --ignore-submodules=all HEAD --; then
        echo 'Uncommitted changes detected:';
        git diff-index HEAD --;
        return 1;
      fi;
    }
script:
  - make DEBUG=1 -j2 compare
  - check_status
after_success:
  - |-
    if [ "$TRAVIS_BRANCH" = master -a "$TRAVIS_PULL_REQUEST" = false -a "$TRAVIS_OS_NAME" = linux ]; then
      ./.travis/webhook.sh
      if [ -n "$GITHUB_API_KEY" ]; then
        ./.travis/upload_symbols.sh
      fi
    fi
