	tilepal 0, ROOF, WATER, GRAY, GREEN, GREEN, BROWN, BROWN, ROOF
	tilepal 0, GREEN, GREEN, GRAY, GRAY, ROOF, RED, GRAY, GRAY
	tilepal 0, GRAY, BROWN, BROWN, GREEN, GREEN, WATER, WATER, WATER
	tilepal 0, GREEN, GREEN, GRAY, GRAY, RED, RED, GRAY, GRAY
	tilepal 0, GRAY, BROWN, BROWN, ROOF, ROOF, WATER, WATER, WATER
	tilepal 0, GREEN, GREEN, GRAY, GRAY, ROOF, GRAY, RED, RED
	tilepal 0, GRAY, BROWN, BROWN, ROOF, ROOF, WATER, WATER, WATER
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, BROWN, BROWN, WATER, GREEN, YELLOW, YELLOW, YELLOW
	tilepal 0, YELLOW, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GREEN, GREEN, ROOF, ROOF, ROOF, YELLOW, YELLOW, YELLOW
	tilepal 0, YELLOW, RED, GRAY, RED, GRAY, GRAY, BROWN, BROWN

rept 16
	db $ff
endr

	tilepal 1, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 1, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 1, ROOF, ROOF, GRAY, GRAY, WATER, BROWN, BROWN, BROWN
	tilepal 1, BROWN, GRAY, BROWN, RED, RED, RED, RED, RED
	tilepal 1, ROOF, ROOF, GRAY, GRAY, ROOF, WATER, BROWN, BROWN
	tilepal 1, BROWN, RED, RED, RED, RED, GRAY, GRAY, GRAY
	tilepal 1, ROOF, ROOF, BROWN, BROWN, ROOF, ROOF, GRAY, GRAY
	tilepal 1, RED, RED, RED, RED, RED, GRAY, RED, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, GRAY, GRAY
	tilepal 1, RED, RED, BROWN, YELLOW, YELLOW, ROOF, GRAY, GREEN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 1, GRAY, BROWN, BROWN, YELLOW, YELLOW, BROWN, BROWN, BROWN
