	tilepal 0, ROOF, WATER, GRAY, GREEN, GREEN, WATER, WATER, ROOF
	tilepal 0, GREEN, GREEN, GRAY, GRAY, RED, RED, GRAY, GRAY
	tilepal 0, GRAY, BROWN, GRAY, GREEN, GREEN, WATER, WATER, WATER
	tilepal 0, GREEN, GREEN, GRAY, GRAY, RED, RED, GRAY, GRAY
	tilepal 0, GRAY, GREEN, GRAY, BROWN, BROWN, WATER, WATER, WATER
	tilepal 0, BROWN, BROWN, GRAY, GRAY, RED, RED, ROOF, ROOF
	tilepal 0, YELLOW, YELLOW, YELLOW, BROWN, BROWN, WATER, WATER, WATER
	tilepal 0, BROWN, BROWN, GRAY, GRAY, RED, RED, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, YELLOW, WATER, GREEN, BROWN, YELLOW, BROWN
	tilepal 0, BROWN, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GREEN, GREEN, BROWN, BROWN, BROWN, YELLOW, WATER, BROWN
	tilepal 0, BROWN, RED, GRAY, RED, GRAY, GRAY, ROOF, ROOF

rept 16
	db $ff
endr

	tilepal 1, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 1, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
