	tilepal 0, GRAY, WATER, GRAY, GREEN, GREEN, GRAY, GRAY, ROOF
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GREEN, GRAY, ROOF, ROOF, GRAY, GRAY, GREEN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, RED, GREEN, GRAY, GRAY, ROOF, ROOF, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, ROOF, GRAY, GRAY, GRAY
	tilepal 0, RED, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN

rept 16
	db $ff
endr

	tilepal 1, BROWN, BROWN, BROWN, ROOF, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, WATER, WATER, BROWN, BROWN, GRAY, BROWN, BROWN
	tilepal 1, BROWN, ROOF, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, ROOF, ROOF, BROWN, BROWN, WATER, BROWN, BROWN
	tilepal 1, BROWN, ROOF, ROOF, ROOF, ROOF, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN, GREEN
	tilepal 1, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, BROWN
	tilepal 1, BROWN, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, WATER, BROWN
	tilepal 1, BROWN, YELLOW, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, ROOF, BROWN
	tilepal 1, YELLOW, YELLOW, YELLOW, GRAY, GREEN, GRAY, GRAY, GRAY
