	tilepal 0, GRAY, WATER, GRAY, GRAY, GRAY, GREEN, GREEN, WATER
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, RED, RED, RED
	tilepal 0, ROOF, GREEN, GRAY, GRAY, WATER, ROOF, ROOF, WATER
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, RED, RED, RED
	tilepal 0, RED, GRAY, GRAY, GRAY, ROOF, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, RED, RED, RED
	tilepal 0, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, RED, RED, RED, RED, GRAY, YELLOW, YELLOW, YELLOW
	tilepal 1, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 1, RED, RED, RED, RED, GRAY, BROWN, BROWN, BROWN
	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 1, RED, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, BROWN, BROWN, ROOF, ROOF, GRAY, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, BROWN, BROWN, ROOF, ROOF, GRAY, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
